version: "3"
services:
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "MyUser"
      POSTGRES_PASSWORD: "Password!23"
      POSTGRES_DB: "sfr-database"
    volumes: 
      - sfr-database-volume:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: "sfr-database"
      DB_USER: "MyUser"
      DB_SCHEMA: keycloak
      DB_PASSWORD: "Password!23"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "Password!23"
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  sfr-database-volume:
    name: sfr-database-volume
    external: true